// Projects Configuration
// Update with your actual projects

export const projects = [
  {
    id: 1,
    title: 'E-Commerce Platform',
    description: 'A modern e-commerce platform with real-time inventory management, payment integration, and advanced search capabilities.',
    fullDescription: 'This comprehensive e-commerce solution was built to handle high traffic and provide seamless shopping experiences. The platform includes features like real-time inventory tracking, secure payment processing, advanced search with filters, and a robust admin dashboard.',
    features: [
      'Real-time inventory management',
      'Secure payment integration with Stripe',
      'Advanced search and filtering',
      'Admin dashboard for product management',
      'Order tracking and notifications',
      'Responsive design for all devices',
    ],
    technologies: ['React', 'TypeScript', 'Next.js', 'Stripe', 'PostgreSQL'],
    image: '🛒', // Replace with '/images/projects/project1.png'
    category: 'Full Stack',
    featured: true,
    liveUrl: 'https://your-project-demo.com', // Add your live demo URL
    githubUrl: 'https://github.com/yourusername/project-name', // Add your GitHub URL
    challenges: 'One of the main challenges was handling real-time inventory updates across multiple users. I solved this by implementing WebSocket connections and optimistic UI updates to ensure data consistency and smooth user experience.',
  },
  {
    id: 2,
    title: 'Dashboard Analytics',
    description: 'Data analytics dashboard with real-time charts, data visualization, and customizable widgets for business intelligence.',
    fullDescription: 'A powerful analytics dashboard that helps businesses make data-driven decisions. Features include real-time data updates, interactive charts, customizable widgets, and export capabilities.',
    features: [
      'Real-time data visualization',
      'Interactive charts with D3.js',
      'Customizable dashboard widgets',
      'Data export functionality',
      'Multiple data source integration',
      'Responsive design',
    ],
    technologies: ['React', 'D3.js', 'TypeScript', 'WebSocket'],
    image: '📊',
    category: 'Frontend',
    featured: true,
    liveUrl: 'https://your-dashboard-demo.com',
    githubUrl: 'https://github.com/yourusername/dashboard',
    challenges: 'Implementing smooth real-time updates without performance degradation was challenging. I used WebSocket connections with data throttling and virtual scrolling to maintain smooth performance even with large datasets.',
  },
  {
    id: 3,
    title: 'Social Media App',
    description: 'Social media application with real-time messaging, feed algorithm optimization, and media handling.',
    fullDescription: 'A full-featured social media platform with real-time messaging, optimized feed algorithms, and comprehensive media handling capabilities.',
    features: [
      'Real-time messaging with Socket.io',
      'Optimized feed algorithm',
      'Image and video upload',
      'User profiles and connections',
      'Notifications system',
      'Mobile-responsive design',
    ],
    technologies: ['React', 'Node.js', 'Socket.io', 'MongoDB'],
    image: '💬',
    category: 'Full Stack',
    featured: false,
    liveUrl: 'https://your-social-app.com',
    githubUrl: 'https://github.com/yourusername/social-app',
    challenges: 'Optimizing the feed algorithm to show relevant content while maintaining performance was complex. I implemented a hybrid approach combining chronological and algorithmic feeds with efficient caching strategies.',
  },
  {
    id: 4,
    title: 'Task Management Tool',
    description: 'Project management tool with kanban board, time tracking, and collaboration features.',
    fullDescription: 'A comprehensive project management solution featuring kanban boards, time tracking, team collaboration, and reporting capabilities.',
    features: [
      'Interactive kanban board',
      'Time tracking and reporting',
      'Team collaboration features',
      'File attachments',
      'Progress tracking',
      'PWA support for offline use',
    ],
    technologies: ['Vue.js', 'TypeScript', 'Firebase', 'PWA'],
    image: '✅',
    category: 'Frontend',
    featured: false,
    liveUrl: 'https://your-task-app.com',
    githubUrl: 'https://github.com/yourusername/task-manager',
    challenges: 'Implementing offline functionality with PWA was challenging. I used service workers with IndexedDB for local storage and implemented conflict resolution strategies for offline edits.',
  },
  {
    id: 5,
    title: 'Learning Platform',
    description: 'Online learning platform with video streaming, interactive quizzes, and progress tracking.',
    fullDescription: 'An educational platform that provides video courses, interactive quizzes, progress tracking, and certification capabilities.',
    features: [
      'Video streaming with adaptive quality',
      'Interactive quizzes and assessments',
      'Progress tracking and certificates',
      'Discussion forums',
      'Mobile app support',
      'Admin course management',
    ],
    technologies: ['Next.js', 'TypeScript', 'Prisma', 'AWS'],
    image: '🎓',
    category: 'Full Stack',
    featured: false,
    liveUrl: 'https://your-learning-platform.com',
    githubUrl: 'https://github.com/yourusername/learning-platform',
    challenges: 'Implementing smooth video streaming with adaptive bitrate was complex. I integrated AWS MediaConvert and CloudFront CDN to ensure optimal video delivery across different network conditions.',
  },
  {
    id: 6,
    title: 'Portfolio Website',
    description: 'Responsive portfolio website with animations, dark mode, and performance optimization.',
    fullDescription: 'A modern, responsive portfolio website showcasing projects and skills with smooth animations and excellent performance.',
    features: [
      'Smooth animations with Framer Motion',
      'Dark mode support',
      'Performance optimized',
      'SEO friendly',
      'Responsive design',
      'Fast loading times',
    ],
    technologies: ['React', 'Framer Motion', 'Vite', 'CSS3'],
    image: '🎨',
    category: 'Frontend',
    featured: false,
    liveUrl: 'https://thvnhtai.app',
    githubUrl: 'https://github.com/yourusername/portfolio',
    challenges: 'Balancing rich animations with performance was key. I used code splitting, lazy loading, and optimized animation triggers to maintain 60fps while providing engaging user experiences.',
  },
]
